baseurl = "https://microbemath.netlify.com/"
languageCode = "en"
title = "A blog of math and microbes"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/mikemc\">Michael McLaren</a> 2019"
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# Syntax highlighting in plain md posts
pygmentsCodeFences  = true
pygmentsStyle = "tango"

[params.sections_left]
"/tags" = "Tags"
"/categories" = "Categories"

[params.sections_right]
"/about" = "About"

[params.features]
# utterances params here

[params.assets]
customCSS = ["css/custom.css"]

[params.rss]
includeContent = true # Includes whole content in rss
authorName = "Michael McLaren" # Site author's full name
authorEmail = "m.mclaren42@gmail.com"

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "math and microbes" # Title for home page
poweredby = false # Adds powered by Hugo and Kiss below Copyright section
related = false # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "mikemc423"
github = "mikemc"
email = "m.mclaren42@gmail.com"
linkedin = ""
gitlab = ""
instagram = ""
codepen = ""
facebook = ""

[params.social.config]
# platforms = ["twitter","github","email","email","linkedin","gitlab"]
platforms = ["twitter","github","email"]

[params.matomoAnalytics]
# siteID = 1
# rootURL = "//matomo.example.com/"

[params.fathomAnalytics]
# rootURL = "//fathom.example.com/"

[taxonomies]
tag ="tags"
category = "categories"

[blackfriday]
hrefTargetBlank = true

